openapi: 3.0.0
info:
  title: HULAF Persons controller
  description: Retrieves persons from database
  version: 0.0.0

definitions:
  MissingPersonDto:
    type: object
    properties:
      guid:
        type: string
      name:
        type: string
  SeekerPersonDto:
    type: object
    properties:
      guid:
        type: string
      name:
        type: string
paths:
  '/missingperson/{personGuid}':
    get:
      tags:
        - person
        - missing
      description: Returns a missing person
      summary: Gets a missing person by guid.
      operationId: getMissingPerson
      responses:
        '200':
          description: Returns a missing person
          summary: Gets a missing person by guid
          content:
            application/json:
              schema:
                $ref: '#/definitions/MissingPersonDto'
    parameters:
      - name: personGuid
        in: path
        description: Guid of person
        schema:
          type: string
          style: simple
  /missingpersonlist:
    get:
      tags:
        - person
        - missing
      description: Returns a missing person list
      summary: Lists missing persons
      operationId: getMissingPersonList
      responses:
        '200':
          description: Missing person list.
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/definitions/MissingPersonDto'
  /seekerperson:
    get:
      summary: A person seeks a missing person
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                $ref: '#/SeekerPersonDto'


