// <auto-generated />
using System;
using System.Collections.Generic;
using HULAF.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HULAF.DataAccess.Migrations
{
    [DbContext(typeof(HULAFContext))]
    partial class HULAFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HULAF.Domain.Person.MissingPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CharacteristicsId");

                    b.Property<Guid?>("LastSeenLocationId");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicsId");

                    b.HasIndex("LastSeenLocationId");

                    b.ToTable("MissingPerson");
                });

            modelBuilder.Entity("HULAF.Domain.PersonCharacteristic.Characteristics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApproxAgeMax");

                    b.Property<int>("ApproxAgeMin");

                    b.Property<int>("ApproxHeight");

                    b.Property<int>("ApproxWeight");

                    b.Property<int>("EyeColor");

                    b.Property<int>("HairColor");

                    b.Property<List<string>>("KnownNames");

                    b.HasKey("Id");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("Location.SeenLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.HasKey("Id");

                    b.ToTable("SeenLocation");
                });

            modelBuilder.Entity("HULAF.Domain.Person.MissingPerson", b =>
                {
                    b.HasOne("HULAF.Domain.PersonCharacteristic.Characteristics", "Characteristics")
                        .WithMany()
                        .HasForeignKey("CharacteristicsId");

                    b.HasOne("Location.SeenLocation", "LastSeenLocation")
                        .WithMany()
                        .HasForeignKey("LastSeenLocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
